### ISSUE TITLE
What is TBSK modulation? =)

### ISSUE THREAD

**Issue by fagci** [nyatla/TBSKmodem#16]
Hello!
What exactly is TBSK modulation? Is there some docs?

**Comment by nyatla** [comment]
Hello.
TBSK modulation is a method of phase-modulating tone signals.
It uses fixed-length symbols much like PSK.

This is a method developed for short-range sound wave communication using media with unknown frequency characteristics.

**Comment by fagci** [comment]
Thank you, got it. And why "trait"? =)

**Comment by nyatla** [comment]
The symbols used by TBSK are tone signals.
I used "Trait" to mean a signal with some kind of characteristic.
(Tone might have been more appropriate.)

**Comment by fagci** [comment]
Got it =)
Good work! =)

Tried to make JavaScript version of FSK modem, best result is with 256-tones with (sadly) FFT, but if I vol up my smartphone, PC with good microphone gets data wo/ errors on distance of 1 room (4 meters). But slow...Think, FT-8 will be better for long distances over audio.

PSK & FSK with autocorellation + additional data for correction not helps for me.
